# Generated by Django 4.2.5 on 2023-10-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField()),
                ('total_amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=255)),
                ('sector_price', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.AutoField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(default='User', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='User', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='stadium.booking')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.sector')),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium'),
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('food_price', models.IntegerField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCoupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_coupons', to='stadium.booking')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('event_description', models.CharField(blank=True, max_length=255, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_items',
            field=models.ManyToManyField(through='stadium.FoodCoupon', to='stadium.fooditem'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.user'),
        ),
    ]
