# Generated by Django 4.2.4 on 2023-10-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_remove_user_city_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
