# Generated by Django 4.2.4 on 2023-10-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0004_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
