# Generated by Django 4.2.4 on 2023-11-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0005_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sector_price',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='capacity',
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_capacity',
            field=models.PositiveIntegerField(default=25000),
        ),
        migrations.CreateModel(
            name='SectorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_price', models.PositiveBigIntegerField()),
                ('remaining_seats', models.PositiveIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.event')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.sector')),
            ],
        ),
    ]
