# Generated by Django 4.2.4 on 2023-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0006_remove_sector_sector_price_remove_stadium_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorprice',
            name='remaining_seats',
            field=models.PositiveIntegerField(blank=True, default=25000, null=True),
        ),
    ]
