# Generated by Django 4.2.4 on 2023-11-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0009_rename_sector_sectorprice_sector_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorprice',
            old_name='event',
            new_name='event_id',
        ),
    ]
