# Generated by Django 4.2.4 on 2023-11-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0010_rename_event_sectorprice_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='food_items',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.sectorprice'),
        ),
    ]
