# Generated by Django 4.2.4 on 2023-11-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0011_remove_booking_food_items_alter_ticket_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
