# Generated by Django 4.2.6 on 2023-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0012_remove_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='coordinates',
            new_name='place_id',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
