# Generated by Django 4.2.6 on 2023-11-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0012_remove_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='coordinates',
            new_name='place_id',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='location',
        ),
    ]
