# Generated by Django 4.2.6 on 2023-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0013_rename_coordinates_stadium_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(null=True),
        ),
    ]
