
# Generated by Django 4.2.6 on 2023-11-17 05:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0015_alter_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='place_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
